### PR TITLE
[BUGFIX] Fix BE/FE misalignement on threshold datamodel #1389

### LINKED ISSUE #1389: Can't save dashboard when setting up a threshold in percentage
### What did you do?

I change a absolute threshold to percentage threshold and save the dashboard.

### What did you expect to see?

Success message

### What did you see instead? Under which circumstances?

Error message: `bad request: invalid panel 1_0: spec.thresholds.mode: 2 errors in empty disjunction: (and 2 more errors)`

### System information

_No response_

### Perses version

_No response_

### Perses configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by AntoineThebaud**
# Description

Changed casing for thresholds mode to kebab-case on frontend side, to align with the backend datamodel. (This was basically missed in https://github.com/perses/perses/pull/1262).

This fixes #1389.

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

### CODE REVIEW

File: ui/e2e/src/pages/PanelEditor.ts [hunk 1]
```diff
@@ -91,7 +91,7 @@ export class PanelEditor {
     await openColorPickerButton.click();
   }
 
-  async toggleThresholdModes(mode: 'Absolute' | 'Percent') {
-    await this.container.getByRole('button', { name: mode === 'Percent' ? 'percent' : 'absolute' }).click();
+  async toggleThresholdModes(mode: 'absolute' | 'percent') {
+    await this.container.getByRole('button', { name: mode === 'percent' ? 'Percent' : 'Absolute' }).click();
```
Comment (AntoineThebaud) [inline ui/e2e/src/pages/PanelEditor.ts:95]: the display remains with capitalized string, hence this selector.

**Review by Gladorme — APPROVED** [review]
LGTM
