### PR TITLE
[ignore] use deep copy in services

### LINKED ISSUE #1960: Can't log in to provisioned users
### What did you do?

1. Clone the repo
2. Start the UI with `npm run start`
3. Start the backend with `./scripts/api_backend_dev.sh`
4. Access Perses at localhost:3000
5. Try to log in with username: `admin`, password: `password`
6. Observe that the log in fails

### What did you expect to see?

I should be able to log in

### What did you see instead? Under which circumstances?

image

### System information

_No response_

### Perses version

0.44.0

### Perses configuration file

_No response_

### Logs

```text
INFO[2024-04-27T16:30:05+10:00]                                               method=POST status=400 uri=/api/auth/providers/native/login
WARN[2024-04-27T16:30:19+10:00] password do not match                         error="crypto/bcrypt: hashedPassword is not the hash of the given password"
```
```

### PR DESCRIPTION
**Pull request by Nexucis**
Counter proposition to #1961.

I'm proposing to make a deep copy of an entity in every services before creating or updating the entity. Like that we ensure that the service can modify the object without modifying the initial reference.

As a side effect it also fixes #1960

### CODE REVIEW

**Comment by Nexucis** [comment]
@sinkingpoint let me know what do you think about this way

File: internal/api/impl/v1/dashboard/service.go [hunk 1]
```diff
@@ -42,47 +45,55 @@ func NewService(dao dashboard.DAO, globalVarDAO globalvariable.DAO, projectVarDA
 }
 
 func (s *service) Create(_ apiInterface.PersesContext, entity *v1.Dashboard) (*v1.Dashboard, error) {
+	copyEntity, err := deep.Copy(entity)
```
Comment (celian-garcia) [inline internal/api/impl/v1/dashboard/service.go:48]: To be safer and ensure we never use the original entity, you could encapsulate all the create logic into a create function and the copy would stay in the Create WDYT ?

Comment (Nexucis) [reply internal/api/impl/v1/dashboard/service.go:48]: ah yes good idea

**Review by celian-garcia — APPROVED** [review]
