### PR TITLE
[BUGFIX] Fix direct link with unknown project redirect now to the home page

### LINKED ISSUE #1349: Direct link to a not existing dashboard/project should error and redirect
Current behavior:

=> Dashboard: empty
image

=> Project: This one is fun, it's not empty but display a fake project
image

### PR DESCRIPTION
**Pull request by Nexucis**
This PR is introducing a sort of guard on the route.

It will check if the project exist and in case it doesn't exist, the user is redirected to the home page.

fix #1349

### CODE REVIEW

File: ui/app/src/model/project-client.ts [hunk 1]
```diff
@@ -112,3 +112,11 @@ export function useDeleteProjectMutation() {
     },
   });
 }
+
+export function fetchProject(name: string) {
```
Comment (celian-garcia) [inline ui/app/src/model/project-client.ts:116]: It is preferrable to make a useProject function using tanstack as it is the direction taken by all the clients. 

If you want to receive a promise, you should use mutation and mutateAsync method

Comment (celian-garcia) [reply ui/app/src/model/project-client.ts:116]: https://tanstack.com/query/v3/docs/react/guides/mutations
https://tanstack.com/query/v3/docs/react/guides/mutations#promises

**Review by celian-garcia — CHANGES_REQUESTED** [review]

File: ui/app/src/model/project-client.ts (hunk 1 above)
Comment (Nexucis) [reply ui/app/src/model/project-client.ts:116]: mutate or mutateAsync is not the correct way when you want to fetch data :/. It's more used when you update or create data

File: ui/app/src/views/ViewDashboard.tsx [hunk 2]
```diff
@@ -161,6 +161,10 @@ function ViewDashboard() {
   }, [actionRef, navigate, projectName]);
 
   if (isLoading) return null;
+  if (error !== null) {
```
Comment (celian-garcia) [inline ui/app/src/views/ViewDashboard.tsx:164]: ``if (error && actionRef.current !== CreateAction) `` ? this is it @Gladorme ?

Comment (Gladorme) [reply ui/app/src/views/ViewDashboard.tsx:164]: Yes

File: ui/app/src/model/project-client.ts (hunk 1 above)
Comment (Nexucis) [reply ui/app/src/model/project-client.ts:116]: I don't really see the value of doing that. Using fetch directly is doing exactly what is expected and it is simpler. Yes it doesn't have a cache or whatever react-query has, but it's not necessary here. The simpler the better

Comment (celian-garcia) [reply ui/app/src/model/project-client.ts:116]: Yes we need to discuss about that custom cache in datasources. I think it should be migrated to react-query. 
I don´t understand what justified the creation of this cache wrapper. Is this historical ? because react-query was not used before? Or is there a specific feature that you make and which is not supported by react-query? Maybe you can explain me. Steven told me he tried also to migrate it to react-query some day, without success.

Comment (celian-garcia) [reply ui/app/src/model/project-client.ts:116]: I guess we can keep it like that as it seems you don't want to have cache for project guard...
