### PR TITLE
BUGFIX: Add Kubebuilder annotation to common.URL

### LINKED ISSUE #2890: Kubebuilder annotation is missing from common.URL
### What did you do?

When trying to add configuration in Perses via the perses-operator the Kubernetes API is trying to validate the common.URL type fields as an object instead of a string and it fails to unmarshal the custom resource.

### What did you expect to see?

The common.URL types can be added as strings in the custom resource and unmarshal works.

### What did you see instead? Under which circumstances?

```
│ W0505 13:27:19.945567       1 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1alpha1.Perses: │
│  json: cannot unmarshal object into Go struct field OIDCProvider.items.spec.config.security.authentication.providers.oidc.discovery_url of type │
│  string
```

### System information

_No response_

### Perses version

_No response_

### Perses configuration file

```yaml

```

### Logs

```text

```

### PR DESCRIPTION
**Pull request by dougkirkley**
# Description

Adds annotations for kubebuilder to properly validate the common.URL type as a string instead of an object

Closes #2890 

# Checklist

- [X] Pull request has a descriptive title and context useful to a reviewer.
- [X] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [X] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

### CODE REVIEW

File: pkg/model/api/v1/common/url.go [hunk 1]
```diff
@@ -48,6 +48,9 @@ func NewURL(u *URL, paths ...string) *URL {
 }
 
 type URL struct {
```
Comment (Nexucis) [inline pkg/model/api/v1/common/url.go:50]: these annotations should go on the above type.

```suggestion
// +kubebuilder:validation:Schemaless
// +kubebuilder:validation:Type=string
// +kubebuilder:validation:Format=uri
type URL struct {
	*url.URL `json:"-" yaml:"-"`
}

**Review by Nexucis — APPROVED** [review]
nice, thanks @dougkirkley !
