### PR TITLE
[BUGFIX] dedicated route for dashboard creation to fix wrong redirections

### LINKED ISSUE #1393: Redirect + Document not found error after succesful dashboard creation when the name contains a space
### What did you do?

- go to project view
- click on Add Dashboard
- Provide a name that contains a space
- Once on the dashboard view, add 1 panel
- Click on save

### What did you expect to see?

Stay on the dashboard view (as when no space is provided in the name)

### What did you see instead? Under which circumstances?

You get redirected to the project page, both document not found error snackbar & dashboard successfully created info snackbar are displayed. The dashboard is available & got created with an underscore instead of the space.

### Perses version

0.39

### PR DESCRIPTION
**Pull request by AntoineThebaud**
# Description

This PR changes:

- the dashboard creation route from `/projects/<project>/dashboards/create` to `/projects/<project>/dashboard/new`. 
  - This fixes a redirection issue we had with the dashboard creation page, i.e the `navigate()` call to standard dashboard view was ignored and the page was instead reloading on `/create`. This was the root cause behind #1393 & also a minor issue not detected previously: in case of successful dashboard creation, reloading the page manually was causing the display of a warning message "document already exists".
  - _NB: side effect of this change: currently when you try to create a dashboard and provide a name that already exists, you get redirected to the existing dashboard instead with a warning "document already exists". Now with this PR, you land on the new dashboard view & will get "document already exists" error if you try to save. To solve the conflict, the only solution currently is to edit the dashboard JSON directly (hence the added condition around warning display on the JSON dialog, since metadata update is possible when creating a new dashboard). This is something we can probably improve in the future with a proper field for name edition. EDIT a simpler solution would be to have some backend validation/check upfront, when providing the initial name in the dashboard creation dialog._

- routes to follow same naming convention & lazy-loading for all (still except the Home page).

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

- [x] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [x] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [ ] Visual tests are stable and unlikely to be flaky. See [Storybook](https://github.com/perses/perses/tree/main/ui/storybook#visual-tests) and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues include:
  - Is the data inconsistent? You need to mock API requests.
  - Does the time change? You need to use consistent time values or mock time utilities.
  - Does it have loading states? You need to wait for loading to complete.

### CODE REVIEW

File: ui/app/src/views/ViewDashboard.tsx [hunk 1]
```diff
@@ -128,7 +128,6 @@ function ViewDashboard() {
           onSuccess: (createdDashboard: DashboardResource) => {
             actionRef.current = undefined;
             successSnackbar(`Dashboard ${getDashboardDisplayName(createdDashboard)} has been successfully created`);
-            navigate(`/projects/${createdDashboard.metadata.project}/dashboards/${createdDashboard.metadata.name}`);
```
Comment (AntoineThebaud) [inline ui/app/src/views/ViewDashboard.tsx:131]: fyi this was basically never called; when `navigate()` call is placed here in this promise, the auto redirection caused by the form submit is taking precedence.

File: ui/dashboards/src/components/SaveDashboardButton/SaveDashboardButton.tsx [hunk 2]
```diff
@@ -67,6 +69,8 @@ export const SaveDashboardButton = ({ onSave, isDisabled, variant = 'contained'
     } else {
       saveDashboard();
     }
+
+    navigate(`/projects/${dashboard.metadata.project}/dashboards/${dashboard.metadata.name}`);
```
Comment (Nexucis) [inline ui/dashboards/src/components/SaveDashboardButton/SaveDashboardButton.tsx:73]: actually we shouldn't do that directly in the dashboards package since you are taking assumption about how the routing is done.

This should come from the parent, that's why initially it was done in the callback of the method `saveDashboard`

File: ui/app/src/views/projects/dashboards/GenericDashboardView.tsx [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+  onDiscard?: (entity: DashboardResource) => void;
+  isReadonly: boolean;
+  isEditing: boolean;
+  isCreating?: boolean;
+}
+
+/**
+ * The View for displaying a Dashboard.
+ */
+export function GenericDashboardView(props: GenericDashboardViewProps) {
```
Comment (AntoineThebaud) [inline ui/app/src/views/projects/dashboards/GenericDashboardView.tsx:39]: Ugly name I know, if you have a better idea feel free to propose :D

File: ui/app/src/views/projects/dashboards/DashboardView.tsx [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+        onError: (err) => {
+          exceptionSnackbar(err);
+          throw err;
+        },
+      });
+    },
+    [exceptionSnackbar, successSnackbar, updateDashboardMutation]
+  );
+
+  const handleDashboardDiscard = useCallback(() => {
```
Comment (Gladorme) [inline ui/app/src/views/projects/dashboards/DashboardView.tsx:63]: callback can be remove `() => undefined`

File: ui/app/src/views/projects/dashboards/CreateDashboardView.tsx [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+  if (!data || data.spec === undefined) return null;
+
+  return (
+    <GenericDashboardView
+      dashboardResource={data}
+      onSave={handleDashboardSave}
+      onDiscard={handleDashboardDiscard}
+      isReadonly={false}
+      isEditing={true}
+      isCreating={true}
```
Comment (AntoineThebaud) [inline ui/app/src/views/projects/dashboards/CreateDashboardView.tsx:105]: In order to display conditionnally the warning message on the Edit JSON dialog (I want it in case of an existing dashboard but not for a new one), I'm obliged to add this new prop `isCreating` at this stage and thus to pass it down repetitively to GenerericDashboardView > ViewDashboard > DashboardApp > EditJsonDialog > EditJsonDialogForm. That's quite a long road but I dont think putting in place a context/provider here would be worth it

File: ui/app/src/views/projects/dashboards/DashboardView.tsx (hunk 4 above)
Comment (Gladorme) [reply ui/app/src/views/projects/dashboards/DashboardView.tsx:63]: Maybe put onDiscard optional if it's not used here

File: ui/app/src/views/projects/dashboards/GenericDashboardView.tsx [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+    datasourceApi.listDatasources(dashboardResource.metadata.project);
+    datasourceApi.listGlobalDatasources();
+  }, [datasourceApi, dashboardResource]);
+
+  // Collect the Project variables and setup external variables from it
+  const { data: globalVars, isLoading: isLoadingGlobalVars } = useGlobalVariableList();
+  const { data: projectVars, isLoading: isLoadingProjectVars } = useVariableList(dashboardResource.metadata.project);
+  const externalVariableDefinitions: ExternalVariableDefinition[] | undefined = useMemo(
+    () => [
+      buildProjectVariableDefinition(dashboardResource.metadata.project, projectVars || []),
```
Comment (Gladorme) [inline ui/app/src/views/projects/dashboards/GenericDashboardView.tsx:54]: It's better to use `??` instead of `||`

Comment (AntoineThebaud) [reply ui/app/src/views/projects/dashboards/GenericDashboardView.tsx:54]: ah ok, this comes from the existing code but I can change it 👍

File: ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx [hunk 7]
```diff
@@ -18,18 +18,24 @@ import { useTimeRange } from '@perses-dev/plugin-system';
 import { useEditJsonDialog } from '../../context/DashboardProvider';
 import { useDashboard } from '../../context/useDashboard';
 
-export const EditJsonDialog = () => {
+export interface EditJsonDialogProps {
+  isCreating?: boolean;
```
Comment (Gladorme) [inline ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx:22]: I think we could use a more generic term for the component: enableMetadataEdition or disableMetadataEdition

Comment (Gladorme) [reply ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx:22]: Because isCreating is related to the user flow, not really the component

File: ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx [hunk 8]
```diff
@@ -18,18 +18,24 @@ import { useTimeRange } from '@perses-dev/plugin-system';
...
+export const EditJsonDialog = (props: EditJsonDialogProps) => {
+  const { isCreating } = props;
   const { editJsonDialog, closeEditJsonDialog } = useEditJsonDialog();
 
   return (
     <Dialog open={!!editJsonDialog?.isOpen} scroll="paper" fullWidth maxWidth="lg">
-      <Dialog.Header onClose={() => closeEditJsonDialog()}>Edit Dashboard</Dialog.Header>
-      {editJsonDialog?.isOpen && <EditJsonDialogForm />}
+      <Dialog.Header onClose={() => closeEditJsonDialog()}>Edit Dashboard JSON</Dialog.Header>
+      {editJsonDialog?.isOpen && <EditJsonDialogForm isCreating={isCreating} />}
```
Comment (Gladorme) [inline ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx:32]: Same for the form "isCreating"

File: ui/app/src/views/projects/dashboards/DashboardView.tsx [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+    // do nothing
+  }, []);
+
+  if (isLoading) return null;
```
Comment (Gladorme) [inline ui/app/src/views/projects/dashboards/DashboardView.tsx:67]: We should but a loader, no? Something like this
``` tsx
{isLoading && (
            <Stack width="100%" sx={{ alignItems: 'center', justifyContent: 'center' }}>
              <CircularProgress />
            </Stack>
          )}
```

File: ui/app/src/views/projects/dashboards/GenericDashboardView.tsx (hunk 3 above)
Comment (Nexucis) [reply ui/app/src/views/projects/dashboards/GenericDashboardView.tsx:39]: what about WrapperDashboardView or HelperDashboardView ?

**Review by Gladorme — APPROVED** [review]
LGTM 😄

File: ui/app/src/views/projects/dashboards/GenericDashboardView.tsx (hunk 3 above)
Comment (AntoineThebaud) [reply ui/app/src/views/projects/dashboards/GenericDashboardView.tsx:39]: Yep that's slightly better I think, I'll go for Helper

**Review by Nexucis — APPROVED** [review]
I added a suggestion to replace the `GenericDashboardView` but otherall looks pretty good.
Well done !
