### PR TITLE
[BUGFIX] Add sort functionality to the Variables

### LINKED ISSUE #3196: ListVariable: Sorting is not working in the preview
### What did you do?

- Open a project
- Go to edit Variable
- You should see the list of preview values
- Change the sort option
- Result: Preview values are not sorted

### What did you expect to see?

The preview values should be sorted accordingly

### More details for you,

Sort is a client-side operation and should be managed by the client. This means, changing the sort should not cause any GET request. At the moment, when the sort option is changed a GET request is sent which is wrong and has no effect. 

Image

Image

## Defected Version

v0.52.0-beta.3

### PR DESCRIPTION
**Pull request by shahrokni**
Closes #3196 

# Description 🖊️ 

This change adds the sort functionality to the Variable Form Editor. 

# The Bug 🐞 

The details can be found here #3196 

# Test 🧪 

Simply add a handful of variables and sort them. Do they get sorted? Save and reload. Is everything in order?  
This should work for any kind of List Variable. 

image

# Checklist

- [X] Pull request has a descriptive title and context useful to a reviewer.
- [X] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [X] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

- [X] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [X] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [X] E2E tests are stable and unlikely to be flaky.
  See [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues include:
  - Is the data inconsistent? You need to mock API requests.
  - Does the time change? You need to use consistent time values or mock time utilities.
  - Does it have loading states? You need to wait for loading to complete.

### CODE REVIEW

File: ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts [hunk 1]
```diff
@@ -12,6 +12,72 @@
...
+      return input.slice().sort((a, b) => a.value.toLowerCase().localeCompare(b.value.toLowerCase()));
+    },
+  },
+  'alphabetical-ci-desc': {
+    label: 'Alphabetical, case-insensitive, desc',
+    sort: (input: VariableOption[]): VariableOption[] => {
+      return input.slice().sort((a, b) => b.value.toLowerCase().localeCompare(a.value.toLowerCase()));
+    },
+  },
+};
```
Comment (AntoineThebaud) [inline ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts:72]: To avoid eventual desynchros in the future, the sorting logics & the ones we already have on the dropdown side should be put in common somehow
https://github.com/perses/perses/blob/35476aaa300e51afef2a6e300a0ae4d85ccc5e4f/ui/dashboards/src/components/Variables/Variable.tsx#L92-L104

Comment (shahrokni) [reply ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts:72]: @AntoineThebaud Do you want me to copy this and use the logic, or have it somewhere and use it for both cases?

Comment (AntoineThebaud) [reply ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts:72]: My point is to have the same piece of code called in both places
