### PR TITLE
[BUGFIX] Take apiPrefix in OIDC/OAuth2 redirections

### LINKED ISSUE #3384: Wrong redirect target after OIDC login
### What did you do?

use keycloak as oidc provider and login to perses with oidc.

OIDC authentication works with a unsightly bug. the final redirect from the logon process points to a wrong url
`https://perses.host.name/perses/api/auth/providers/oidc/keycloak/`
but should be: `https://perses.host.name/perses` (base url of perses)

### What did you expect to see?

after a succesful oidc login a redirect to perses base url: `https://perses.host.name/perses`

### System information

Linux 6.6.103 x64_64

### Perses version

0.52.0

### Perses configuration file

```yaml
api_prefix: /perses
database:
  file:
    extension: json
    folder: /perses
frontend:
  explorer:
    enable: true
  important_dashboards: []
provisioning:
  folders:
  - /etc/perses/provisioning
  interval: 5m
security:
  authentication:
    disable_sign_up: true
    providers:
      enable_native: true
      oidc:
      - client_id: perses-oidc-client
        http:
          tls_config:
            caFile: /ca/ca.crt
        issuer: https://test-keycloak.host.name/realms/test
        name: Keycloak
        redirect_uri: https://perses.host.name/perses/api/auth/providers/oidc/keycloak/callback
        scopes:
        - openid
        - profile
        - email
        - roles
        slug_id: keycloak
  cookie:
    same_site: lax
    secure: false
  enable_auth: true
  readonly: false
```

### Logs

```text
* no log messages from perses container
* in the browser you get: `{"message":"Not Found"}` with HTTP/404
```

### PR DESCRIPTION
**Pull request by celian-garcia**
# Description

fix #3384

# Screenshots

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

No UI CHanges

### CODE REVIEW

File: internal/api/impl/auth/auth.go [hunk 1]
```diff
@@ -258,9 +259,11 @@ func encodeOAuthState(redirectPath string) string {
 	return fmt.Sprintf("%s%s%s", randomPart, stateSeparator, redirectPath)
 }
 
+// decodeOAuthState extracts the redirect path from the state string.
+// If the format is invalid or the redirect path is missing, returns an empty string.
 func decodeOAuthState(state string) string {
 	parts := strings.SplitN(state, stateSeparator, 2)
-	if len(parts) == 2 {
+	if len(parts) == 2 && len(parts[1]) > 0 {
```
Comment (celian-garcia) [inline internal/api/impl/auth/auth.go]: Oh I didn't see copilot added that. I will revert as it doesn't bring anything. I will let the doc though

File: internal/api/impl/auth/auth.go [hunk 2]
```diff
@@ -71,12 +71,13 @@ func getRootURL(r *http.Request) url.URL {
...
+	u.Path = apiPrefix
 	return u
 }
 
-func getRedirectURI(r *http.Request, authKind string, slugID string) string {
-	rd := getRootURL(r)
-	rd.Path = fmt.Sprintf("%s/%s/%s/%s/%s", utils.APIPrefix, utils.PathAuthProviders, authKind, slugID, utils.PathCallback)
+func getRedirectURI(r *http.Request, authKind, slugID, apiPrefix string) string {
+	rd := getRootURL(r, apiPrefix)
+	rd.Path += fmt.Sprintf("%s/%s/%s/%s/%s", utils.APIPrefix, utils.PathAuthProviders, authKind, slugID, utils.PathCallback)
```
Comment (Nexucis) [inline internal/api/impl/auth/auth.go:80]: in case `getRootURL` is used only in `getRedirectURI` it will be simpler if the apiPrefix is appended here

Comment (celian-garcia) [reply internal/api/impl/auth/auth.go:80]: no getRootURL is used in the logout. I need the api prefix there
