### PR TITLE
[BUGFIX] Tooltip positioning broken in Firefox

### LINKED ISSUE #1396: (Firefox only) Timeseries panel: series tooltip on hover is shaky when moving around
### What did you do?

Using Mozilla Firefox, hover on a timeseries panel to display the series tooltip, and move around.

https://github.com/perses/perses/assets/7058693/55e7b2f9-3db9-48e7-874e-f25a67c01642

### What did you expect to see?

Stable tooltip to be able to read it while moving.

### What did you see instead? Under which circumstances?

Shaking tooltip that makes it impossible to read.

### Perses version

```text
0.39
```

### PR DESCRIPTION
**Pull request by sjcobb**
# Description
Fixes #1396

Tooltip is broken in Firefox, fix up the mousemove logic (offsetX and offsetY have subtle differences with Chrome)

zrender is the canvas/svg graphics lib that ECharts is built on, main change is to always use their mousemove coords that [handle browser inconsistencies](https://github.com/ecomfe/zrender/blob/5.5.0/src/core/event.ts#L46-L120) for us

# Screenshots

## Before
https://github.com/perses/perses/assets/9369625/f8d9433e-4147-47fc-bae7-87ccf86242b1

Also see recording in #1396

## After

https://github.com/perses/perses/assets/9369625/a346979d-e143-452f-a3fc-e4f3b065ca57

https://github.com/perses/perses/assets/9369625/8f7ec20a-1d7e-4f13-b99f-31f37f1b4ab3

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the
  following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `DOC`,`IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

- [x] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [x] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [x] Visual tests are stable and unlikely to be flaky.
  See [Storybook](https://github.com/perses/perses/tree/main/ui/storybook#visual-tests)
  and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues
  include:
  - Is the data inconsistent? You need to mock API requests.
  - Does the time change? You need to use consistent time values or mock time utilities.
  - Does it have loading states? You need to wait for loading to complete.

### CODE REVIEW

File: ui/components/src/utils/chart-actions.ts [hunk 1]
```diff
@@ -56,14 +56,17 @@ export function restoreChart(chart: EChartsInstance) {
  * Clear all highlighted series when cursor exits canvas
  * https://echarts.apache.org/en/api.html#action.downplay
  */
-export function clearHighlightedSeries(chart: EChartsInstance, totalSeries: number) {
+export function clearHighlightedSeries(chart: EChartsInstance) {
   if (chart.dispatchAction !== undefined) {
-    for (let i = 0; i < totalSeries; i++) {
```
Comment (sjcobb) [inline ui/components/src/utils/chart-actions.ts:61]: Not directly related to the Firefox issue, but ECharts doesn't actually require you set an explicit seriesIndex this way in dispatchAction. It can automatically "unhighlight" the correct series (which is way better for perf when moving your cursor between quickly between panels)

File: ui/components/src/TimeSeriesTooltip/tooltip-model.ts [hunk 2]
```diff
@@ -109,12 +110,9 @@ export const useMousePosition = (): CursorData['coords'] => {
           y: e.clientY,
         },
         plotCanvas: {
-          x: e.offsetX,
```
Comment (sjcobb) [inline ui/components/src/TimeSeriesTooltip/tooltip-model.ts:112]: See inline comment below, this is the most important part of the fix to use [zrender](https://github.com/ecomfe/zrender) mousemove coords

File: ui/components/src/LineChart/LineChart.tsx [hunk 3]
```diff
@@ -123,11 +123,11 @@ export const LineChart = forwardRef<ChartInstance, LineChartProps>(function Line
             // when chart undef, do not clear highlight series
             return;
           }
-          clearHighlightedSeries(chartRef.current, data.timeSeries.length);
+          clearHighlightedSeries(chartRef.current);
         },
       };
     },
-    [data.timeSeries.length]
+    []
```
Comment (sjcobb) [inline ui/components/src/LineChart/LineChart.tsx:130]: This entire component LineChart.tsx that uses 'category' xAxis should be deprecated and removed, it was replaced by TimeChart a while back in #1268

File: ui/components/src/TimeSeriesTooltip/LineChartTooltip.tsx [hunk 4]
```diff
@@ -59,7 +59,7 @@ export const LineChartTooltip = memo(function LineChartTooltip({
   const [showAllSeries, setShowAllSeries] = useState(false);
   const mousePos = useMousePosition();
   const { height, width, ref: tooltipRef } = useResizeObserver();
-  const transform = useRef('');
+  const transform = useRef<string | undefined>();
```
Comment (sjcobb) [inline ui/components/src/TimeSeriesTooltip/LineChartTooltip.tsx:62]: Fixed these since type errors were thrown, but LineChartTooltip can also be removed now, as well as legacyCheckforNearbySeries and [getLineSeries](https://github.com/perses/perses/blob/8cf6c9af4ce7d17523269f28fbecc41258dd14f3/ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts#L71) (see [other comment](https://github.com/perses/perses/pull/1750/files#r1482388936))

File: ui/panels-plugin/src/plugins/scatterplot/Scatterplot.tsx [hunk 5]
```diff
@@ -60,7 +60,9 @@ export function Scatterplot(props: ScatterplotProps) {
       axisPointer: {
         type: 'cross',
       },
+      // eslint-disable-next-line @typescript-eslint/no-explicit-any
       formatter: function (params: any) {
```
Comment (sjcobb) [inline ui/panels-plugin/src/plugins/scatterplot/Scatterplot.tsx:64]: This [threw lint errors](https://github.com/perses/perses/actions/runs/7824675331/job/21347614114) on my PR, but should have been caught in #1672, wonder if something is up with PR checks 😕 (added TODO for changing `any` to import directly from ECharts types)

Comment (sjcobb) [reply ui/panels-plugin/src/plugins/scatterplot/Scatterplot.tsx:64]: Oh I guess no-explicit-any is just a warning so won't fail that check, but probably should be an error

**Comment by celian-garcia** [comment]
Cool ! Any chance that it solves the #1497 as well ? This was occuring on chrome, the top lines was not triggering the tooltip and the lines were highlighted all at once everytime, if I remember well

**Review by AntoineThebaud — APPROVED** [review]
awesome! thanks for fixing this 🙏

**Review by Nexucis — APPROVED** [review]
niiiicceee ! Thanks 🙏

**Comment by sjcobb** [comment]
> Cool ! Any chance that it solves the #1497 as well ? This was occuring on chrome, the top lines was not triggering the tooltip and the lines were highlighted all at once everytime, if I remember well

Ah, nah that’s a different issue, we loop through the raw dataset values in our custom tooltip so it doesn’t account for aggregated values in our stacked variant correctly, but we can actually just use the ECharts [mouseover event](https://echarts.apache.org/en/api.html#events.Mouse%20events.mouseover) to find the correct series when isStacked since they won’t overlap.

Just assigned myself that one!
