### PR TITLE
[BUGFIX] datasource form: make name readonly after creation + fix wrong titles/names in readonly mode

### LINKED ISSUE #1356: Edit global datasource name if default
When we edit the datasource name it is doing a create + delete actions. 
But if it is default, then we create a second default which is not authorized.
image

### PR DESCRIPTION
**Pull request by AntoineThebaud**
# Description

fixes https://github.com/perses/perses/issues/1356.

This PR brings small changes to the datasource creation/edit form:
- it makes the datasource name attribute readonly after creation. This fixes the bug raised with #1356. The decision to remove this feature comes from other reasons than just this fix, see the comments in this issue to have more context.
image
- it fixes some wrong titles/names in readonly mode.
image
- it also aligns variable & datasource forms behaviors when clicking out of the drawer: it's now doing nothing for both - until we find a proper solution to have closure with discard confirmation modal showing up in this situation.

# Checklist

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] Pull request title follows the `[<catalog_entry>] <commit message>` naming convention using one of the following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, `IGNORE`.
- [x] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).

## UI Changes

- [x] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [x] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [x] Visual tests are stable and unlikely to be flaky. See [Storybook](https://github.com/perses/perses/tree/main/ui/storybook#visual-tests) and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues include:
  - Is the data inconsistent? You need to mock API requests.
  - Does the time change? You need to use consistent time values or mock time utilities.
  - Does it have loading states? You need to wait for loading to complete.

### CODE REVIEW

File: ui/app/src/components/DatasourceList/DatasourceEditorForm.tsx [hunk 1]
```diff
@@ -134,7 +134,7 @@ export function DatasourceEditorForm<T extends Datasource>(props: DatasourceEdit
               label="Name"
               value={state.metadata.name}
               InputProps={{
-                readOnly: isReadonly,
+                readOnly: saveActionStr !== 'Create',
```
Comment (celian-garcia) [inline ui/app/src/components/DatasourceList/DatasourceEditorForm.tsx:137]: Not linked with this PR but the saveActionStr could be a limited string.
It would prevent from a developer to create the component with ``saveActionStr='new'`` for example, and would be more future proof

Comment (celian-garcia) [reply ui/app/src/components/DatasourceList/DatasourceEditorForm.tsx:137]: e.g the `action` prop in `VariableFormDrawer`

Comment (AntoineThebaud) [reply ui/app/src/components/DatasourceList/DatasourceEditorForm.tsx:137]: Oh didnt check I thought it was already done, let me check

**Comment by celian-garcia** [comment]
FYI, If you put "fixes #1356" in the description of the PR, it will close automatically the issue when PR merged

**Review by celian-garcia — APPROVED** [review]
